apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: watchparty
type: Opaque
stringData:
  POSTGRES_USER: "watchparty"
  POSTGRES_PASSWORD: "CHANGE_ME"
  POSTGRES_DB: "watchparty"
